title: Sandeep Hirnaik
logo: /Images/San1.png
email: sanndeeph@gmail.com
linkedin_username: sandeep-h
github_username:  sanndeeph
description: Senior Analyst - Data & Analytics @ Eversana <br><br>
Experienced Senior Analyst in various domains, currently in the pharmaceutical domain with a total of 14+ years of experience. Proficient in developing impactful dashboards using Tableau, Power BI, and Google Looker Studio. Skilled in data extraction, analysis, and reporting, optimizing processes with tools like Alteryx, SQL queries, and excel automation. Collaborative team player, proficient at planning reporting strategies and providing mentorship. Currently acquiring Python, R, Hadoop, Data science skills by self study.
show downloads: true
links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/sanndeeph   
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/sandeep-h/
    - label: "email"
      icon: "fab fa-fw fa-email"
      url: sanndeeph@gmail.com
theme: jekyll-theme-minimal
