title: Sandeep H
logo: /Images/San1.png
linkedin_username: sandeep-h
description: 
show downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-minimal
