title: Sandeep Hirnaik
logo: /Images/San1.png
email: sanndeeph@gmail.com
linkedin_username: sandeep-h
github_username:  sanndeeph
description: Senior Analyst - Data & Analytics @ Eversana
show downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jemoji
