title: Sandeep Hirnaik
logo: /Images/San1.png
email: sanndeeph@gmail.com
linkedin_username: sandeep-h
github_username:  sanndeeph
description: Senior Analyst - Data & Analytics @ Eversana
show downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
