title: Sandeep Hirnaik
logo: /Images/San1.png
description: Senior Analyst - Data & Analytics @ Eversana
show_downloads: true
links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/sanndeeph   
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/sandeep-h/
    - label: "email"
      icon: "fab fa-fw fa-email"
      url: sanndeeph@gmail.com
theme: jekyll-theme-minimal
